### ISSUE TITLE
Add attribute_name to Field

### ISSUE THREAD

**Issue by numberoverzero** [stevearc/flywheel#16]
This is an absolutely fantastic library, by the way.

---

Since attribute names count against the 64kb limit for items and against provisioned iops ([docs](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html)), it would be great to specify a short attribute name, and still refer to the field by a longer name.

For example:

```
class MyModel(Model):
    my_long_id = Field(hash_key=True, data_type=BINARY, attribute_name='id')
    unreasonably_long_field_name_for_data = Field(attribute_name='data')
```

I imagine that all external references would still use the model's meta field names - `my_long_id` - which would require an extra field_name -> attribute_name translation when constructing queries.  Fallback when attribute_name isn't specified would use the existing behavior.

If you're interested, I can get to work on a pr.

---

This came about because I tried to change the name of a field before mapping it to an object as a workaround, but it didn't persist.  That seems odd - maybe it's worth checking if field name is None [here](https://github.com/mathcamp/flywheel/blob/master/flywheel/model_meta.py#L190) before overwriting it?

A simple test case:

```
f = Field(hash_key=True)
f.name = 'custom name'
print(f.name)  # prints 'custom name'
class MyModel(Model):
    id = f
print(MyModel.id.name)  # prints 'id'
print(f.name)  # prints 'id'
```

**Comment by natecode** [comment]
This is a good idea. It should be easy to check all attribute short names for collisions in `engine.register()` for each model, that way you could raise an error early.

**Comment by numberoverzero** [comment]
Closing this out since I've moved to a different project.

There's been a number of improvements in flywheel since the original PR; it's probably easier to start fresh than try to pick up where it left off.
