### ISSUE TITLE
engine.create_schema() doesn't add newly added global indexes for existing tables.

### ISSUE THREAD

**Issue by aronkyle-lightspeedretail** [stevearc/flywheel#52]
It's possible this might be better accomplished with a new engine.update_schema() function.

dynamo3 already has the describe() and update_table() functions required. It's just a matter to doing a diff between what global indexes should be there and which ones shouldn't.

**Comment by stevearc** [comment]
Fixed by https://github.com/stevearc/flywheel/pull/53 (Thanks for the PR!)
Released in [0.5.1](https://pypi.python.org/pypi/flywheel/0.5.1)
