### ISSUE TITLE
Documentation references support for undeclared / overflow fields 

### ISSUE THREAD

**Issue by DaineDanielson** [stevearc/flywheel#54]
Unless I'm mistaken, undeclared / overflow field support was removed in version 5.0.0,
https://github.com/stevearc/flywheel/commit/5cf757e1e1a2d6b3caf6ebf6732e7af36ba4b6cc

but support for undeclared fields is still mentioned in the documentation here:
https://github.com/stevearc/flywheel/blame/master/doc/topics/models/basics.rst#L18

I'm new to your library, so I hope I'm not missing something. If so, please disregard.

**Comment by stevearc** [comment]
Good catch! I probably missed that when I made the change because I was grepping for "overflow" instead of "undeclared". I'll get that fixed up :)

**Comment by bobcolner** [comment]
Just adopted this great lib (thanks!) but I also got bit by the documentation:

> Since DynamoDB has no schema, you can set arbitrary fields 

I'm sure you had good reasons to remove this capability from Flywheel. It would be really helpful if
1) If you could explain why this was removed.
2) Suggests an alternate workflow using flywheel 0.5+ to support adding adhoc fields (update and reregister the schema? -this didn't work for me)

Thanks

**Comment by stevearc** [comment]
Another great find! This is what I get for not using consistent terminology for a feature. It's impossible to grep during a refactor.

The main reason this was removed from flywheel was that it was unexpected, "magic" behavior that frequently collided with what you were trying to do. If you make a model and want to store some local state on it, you have to know that those variables need to start with an underscore or flywheel will magically stick them into your database. Also the way we were tracking that was with `__setattr__` and there were some...very interesting, very horrible crashes you could hit if your model needed to also override `__setattr__` or in some cases with `@property`.

The way the workflow should go 95% of the time is you know ahead of time all of the fields that you want stored in the DB rows, so you declare them on your model. You want to store something new? Just add a new Field. Don't want to store something? Remove the Field. That won't change the actual data in the database, but if your application is tolerant of nulls then that's all you have to do.

The remaining 5% of the time you may have fields you need to store that are dynamically generated, so you can't declare them as a Field. In that case, the easiest thing to do would be to store all of those as keys in a single Map field (e.g. `extras = Field(type=dict)`).

If you have a different use case, or the above workflows aren't working for you, feel free to file another issue or shoot me an email!

**Comment by bobcolner** [comment]
>  and there were some...very interesting, very horrible crashes you could hit if your model needed to also override __setattr__ or in some cases with @property.

wow, better off without it. I went with the 'meta' MAP field for my dynamic stuff.
