### ISSUE TITLE
can save return the items new values?

### ISSUE THREAD

**Issue by BrandonBraner** [stevearc/flywheel#61]
By default, I believe DynamoDB returns the updates item for free.
Is it possible to get the save method on a Model to return the saved items?

Maybe it already does, I haven't dug through the code too much yet.

**Comment by stevearc** [comment]
When using the `sync()` method flywheel will perform an [UpdateItem](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateItem.html) and specify [returns=ALL_NEW](https://github.com/stevearc/flywheel/blob/99b2bc39b7c621bd3a6ec18e023dd28524b62a58/flywheel/engine.py#L654-L656). It then updates the models with the returned values.
