### ISSUE TITLE
dynamo3 dependency released breaking change

### ISSUE THREAD

**Issue by mcchong** [stevearc/flywheel#67]
I realize this is an unsupported library, but for anyone still using it, it appears the dynamo3 package just released a new version with some breaking changes.  If you are missing a typing_extensions module suddenly, you may want to specify `dynamo3==0.4.10` in your requirements.txt as a workaround.

**Comment by stevearc** [comment]
I added a version constraint for dynamo3<1.0 and released a new patch version 0.5.4
Should be fixed now. Thanks for the report!
